name: Encountering an Issue
description: Please provide details about the issue you are encountering
labels: [bug]
body:
  - type: input
    id: site-url
    validations:
      required: true
    attributes:
      label: "Site URL"
      placeholder: "Please provide the URL of the site where the issue occurred"
  - type: input
    id: problem
    attributes:
      label: "Description of the Issue"
      description: "Include any error messages or screenshots if applicable"
      placeholder: "Please describe the issue you are encountering"
  - type: textarea
    id: other
    attributes:
      label: "Additional Information"
      description: "Is there anything else you would like to add?"
