name: 遇到问题
description: 请填写遇到的问题的详细信息
labels: [bug]
body:
  - type: input
    id: site-url
    validations:
      required: true
    attributes:
      label: "站点链接"
      placeholder: "请填写你的站点链接"
  - type: input
    id: problem
    attributes:
      label: "问题描述"
      description: "有错误的话请提供报错截图"
      placeholder: "请详细描述一下遇到的问题"
  - type: textarea
    id: other
    attributes:
      label: "补充信息"
      description: "还需要说些什么吗"
