name: Other Information
description: Any other issues or questions related to usage
labels: [other]
body:
  - type: textarea
    id: title
    attributes:
      label: "Description of the Issue"
      description: "Please provide a clear description of the issue you are experiencing"
  - type: textarea
    id: other
    attributes:
      label: "Additional Information"
      description: "Is there any other information you would like to add?"