# Dev 分支推送部署预览
## 仅部署 Win 端
name: Build

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    name: Build Website
    runs-on: windows-latest

    steps:

      # 检出 Git 仓库
      - name: Check out git repository
        uses: actions/checkout@v4.1.1

      # 安装 Node.js
      - name: Install Node.js
        uses: actions/setup-node@v4.0.0
        with:
          node-version: "20.x"

      # 安装项目依赖
      - name: Install Dependencies
        run: | 
          npm install -g pnpm
          pnpm install

      # 构建程序
      - name: Build Website
        run: pnpm build
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
     
      # 上传构建产物
      - name: Add changes to git
        run: |
          git add .

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Auto build #  Change here to the commit message